force-app/main/default/objects/Condition_Set__c/Condition_Set__c.object-meta.xml
<CustomObject>
    <label>Condition Set</label>
    <nameField>
        <label>Condition Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition_Set__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Action</relationshipLabel>
    <relationshipName>Action</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScoringAdminControllerTest.cls
@isTest
private class ScoringAdminControllerTest {

    @testSetup
    static void seedData() {

    }

    @isTest
    static void testSaveConditionSet() {
        Map<String,Object> conditionSetMap = new Map<String,Object>();
        List<Map<Object,Object>> lineItems = new List<Map<Object,Object>>();
        conditionSetMap.put('lineItems', lineItems);
        conditionSetMap.put('description', 'test conditions');
        conditionSetMap.put('conditionDirection', 'Add');
        conditionSetMap.put('scoreType', 'fit');
        conditionSetMap.put('value', 5);
        conditionSetMap.put('active', true);
        conditionSetMap.put('logicalStatement', '1');
        conditionSetMap.put('objectType', 'Lead');
        Map<Object,Object> lineItem = new Map<Object,Object>();
        lineItems.add(lineItem);
        lineItem.put('field', 'Name');
        lineItem.put('operand', 'x');
        lineItem.put('operator', '=');
        lineItem.put('ruleNumber', 1);

        ScoringAdminController.saveConditionSet(conditionSetMap);
        List<Action__c> newActions = [SELECT Id FROM Action__c];
        List<Condition_Set__c> newConditionSets = [SELECT Id FROM Condition_Set__c];
        System.assert(!newActions.isEmpty(),
            'Action not created');
        System.assert(!newConditionSets.isEmpty(),
            'Condition Set not created');
        Id actionId = newActions[0].Id;
        Id conditionSetId = newConditionSets[0].Id;

        conditionSetMap.put('actionId', actionId);
        conditionSetMap.put('id', conditionSetId);
        ScoringAdminController.saveConditionSet(conditionSetMap);
        ScoringAdminController.deleteAction(actionId);
        System.assert(true);
    }

    @isTest
    static void testGetAdminView() {
        Map<String,Object> adminView = ScoringAdminController.getAdminView(null);
        System.assert(adminView.containsKey('conditionSets'));
    }
}