force-app/main/default/objects/Condition_Set__c/Condition_Set__c.object-meta.xml
<CustomObject>
    <label>Condition Set</label>
    <nameField>
        <label>Condition Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition_Set__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Action</relationshipLabel>
    <relationshipName>Action</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Condition_Set__c/fields/Logical_Statement__c.field-meta.xml
<CustomField>
    <fullName>Logical_Statement__c</fullName>
    <label>Logical Statement</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Condition_Set__c/fields/RPN_Logic__c.field-meta.xml
<CustomField>
    <fullName>RPN_Logic__c</fullName>
    <label>RPN Logic</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ConditionSetTriggerTest.cls
@isTest
private class ConditionSetTriggerTest {

    @testSetup
    static void seedData() {

    }

    @isTest
    static void testLogicConversion() {
        Action__c testAction = new Action__c();
        insert testAction;
        Condition_Set__c testConditionSet = new Condition_Set__c(
            Action__c = testAction.Id,   
            Logical_Statement__c = '1 AND (2 OR 3)'
        );
        insert testConditionSet;
        testConditionSet = [SELECT RPN_Logic__c FROM Condition_Set__c WHERE Id = :testConditionSet.Id];
        System.assert(testConditionSet.RPN_Logic__c != null,
            'Logic not converted.');
    }


}