force-app/main/default/objects/Action__c/fields/Action_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Action_Frequency__c</fullName>
    <description>How often the action should be applied</description>
    <label>Action Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Frequencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action__c/fields/Positive__c.field-meta.xml
<CustomField>
    <fullName>Positive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Score_Type__c.field-meta.xml
<CustomField>
    <fullName>Score_Type__c</fullName>
    <label>Score Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Condition_Line_Item__c/Condition_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Condition Line Item</label>
    <nameField>
        <label>Condition Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition_Line_Item__c/fields/Condition_Set__c.field-meta.xml
<CustomField>
    <fullName>Condition_Set__c</fullName>
    <label>Condition Set</label>
    <referenceTo>Condition_Set__c</referenceTo>
    <relationshipLabel>Condition Set Line Items</relationshipLabel>
    <relationshipName>Condition_Set_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Condition_Line_Item__c/fields/Operand__c.field-meta.xml
<CustomField>
    <fullName>Operand__c</fullName>
    <label>Operand</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Condition_Line_Item__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>!=</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>startsWith</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>doesNotStartWith</fullName>
            </value>
            <value>
                <fullName>doesNotContain</fullName>
            </value>
            <value>
                <fullName>isNull</fullName>
            </value>
            <value>
                <fullName>isNotNull</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Condition_Line_Item__c/fields/Rule_Number__c.field-meta.xml
<CustomField>
    <fullName>Rule_Number__c</fullName>
    <label>Rule Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Condition_Set__c/Condition_Set__c.object-meta.xml
<CustomObject>
    <label>Condition Set</label>
    <nameField>
        <label>Condition Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition_Set__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Action</relationshipLabel>
    <relationshipName>Action</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Condition_Set__c/fields/Logical_Statement__c.field-meta.xml
<CustomField>
    <fullName>Logical_Statement__c</fullName>
    <label>Logical Statement</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Condition_Set__c/fields/RPN_Logic__c.field-meta.xml
<CustomField>
    <fullName>RPN_Logic__c</fullName>
    <label>RPN Logic</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Action_Frequencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Always</fullName>
    </customValue>
    <customValue>
        <fullName>Hourly</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <description>How often a score should be applied.</description>
    <masterLabel>Action Frequencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConditionUtilityTest.cls
@isTest
private class ConditionUtilityTest {

    @testSetup
    static void seedData() {
        Action__c newAction = new Action__c();
        insert newAction;
        Condition_Set__c cs = new Condition_Set__c(
            Action__c = newAction.Id,
            Logical_Statement__c = '1 OR (2 AND 3) OR 4 OR 5 OR 6 OR 7 OR 8 OR 9',
            Object_Type__c = 'Lead'
        );
        insert cs;
        Condition_Line_Item__c cli1 = new Condition_Line_Item__c(
            Condition_Set__c = cs.Id,
            Field__c = 'Name',
            Operator__c = 'isNull',
            Operand__c = 'true',
            Rule_Number__c = 1
        );
        Condition_Line_Item__c cli2 = new Condition_Line_Item__c(
            Condition_Set__c = cs.Id,
            Field__c = 'Name',
            Operator__c = 'isNotNull',
            Operand__c = 'true',
            Rule_Number__c = 2
        );
        Condition_Line_Item__c cli3 = new Condition_Line_Item__c(
            Condition_Set__c = cs.Id,
            Field__c = 'Name',
            Operator__c = '=',
            Operand__c = 'XYZ',
            Rule_Number__c = 3
        );
        Condition_Line_Item__c cli4 = new Condition_Line_Item__c(
            Condition_Set__c = cs.Id,
            Field__c = 'Name',
            Operator__c = 'contains',
            Operand__c = 'a',
            Rule_Number__c = 4
        );
        Condition_Line_Item__c cli5 = new Condition_Line_Item__c(
            Condition_Set__c = cs.Id,
            Field__c = 'Name',
            Operator__c = 'IN',
            Operand__c = 'a,b,c',
            Rule_Number__c = 5
        );
        Condition_Line_Item__c cli6 = new Condition_Line_Item__c(
            Condition_Set__c = cs.Id,
            Field__c = 'Name',
            Operator__c = 'doesNotContain',
            Operand__c = 'x',
            Rule_Number__c = 6
        );
        Condition_Line_Item__c cli7 = new Condition_Line_Item__c(
            Condition_Set__c = cs.Id,
            Field__c = 'Name',
            Operator__c = 'startsWith',
            Operand__c = 'x',
            Rule_Number__c = 7
        );
        Condition_Line_Item__c cli8 = new Condition_Line_Item__c(
            Condition_Set__c = cs.Id,
            Field__c = 'NumberOfEmployees',
            Operator__c = '<=',
            Operand__c = '50',
            Rule_Number__c = 8
        );
        Condition_Line_Item__c cli9 = new Condition_Line_Item__c(
            Condition_Set__c = cs.Id,
            Field__c = 'IsConverted',
            Operator__c = '!=',
            Operand__c = 'true',
            Rule_Number__c = 9
        );
        insert cli1;
        insert cli2;
        insert cli3;
        insert cli4;
        insert cli5;
        insert cli6;
        insert cli7;
        insert cli8;
        insert cli9;
    }

    @isTest
    static void testObjectMeetsConditionSet() {
        Lead newLead = new Lead(LastName = 'Testly', Company = 'Test Co.', Email = 'xyz@test.com');
        insert newLead;
        List<Condition_Set__c> css = [SELECT
            Id, Logical_Statement__c, RPN_Logic__c, Object_Type__c, Description__c,
            (SELECT Field__c, Field_Type__c, Operand__c, Operator__c, Rule_Number__c FROM Condition_Set_Line_Items__r),
            Action__c, Action__r.Positive__c, Action__r.Score_Type__c,
            Action__r.Value__c, Action__r.Action_Frequency__c
            FROM Condition_Set__c];
        Boolean outcome = ConditionUtility.objectMeetsConditionSet(newLead, css[0]);
        System.assert(outcome != null,
            'Condition not evaluated successfully');
    }

}