force-app/main/default/objects/Action__c/fields/Positive__c.field-meta.xml
<CustomField>
    <fullName>Positive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Score_Type__c.field-meta.xml
<CustomField>
    <fullName>Score_Type__c</fullName>
    <label>Score Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Engagement_Score__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Score__c</fullName>
    <label>Engagement Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Condition_Line_Item__c/Condition_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Condition Line Item</label>
    <nameField>
        <label>Condition Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition_Line_Item__c/fields/Condition_Set__c.field-meta.xml
<CustomField>
    <fullName>Condition_Set__c</fullName>
    <label>Condition Set</label>
    <referenceTo>Condition_Set__c</referenceTo>
    <relationshipLabel>Condition Set Line Items</relationshipLabel>
    <relationshipName>Condition_Set_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Condition_Line_Item__c/fields/Operand__c.field-meta.xml
<CustomField>
    <fullName>Operand__c</fullName>
    <label>Operand</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Condition_Line_Item__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>=</fullName>
            </value>
            <value>
                <fullName>!=</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>startsWith</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>doesNotStartWith</fullName>
            </value>
            <value>
                <fullName>doesNotContain</fullName>
            </value>
            <value>
                <fullName>isNull</fullName>
            </value>
            <value>
                <fullName>isNotNull</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Condition_Line_Item__c/fields/Rule_Number__c.field-meta.xml
<CustomField>
    <fullName>Rule_Number__c</fullName>
    <label>Rule Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Condition_Set__c/Condition_Set__c.object-meta.xml
<CustomObject>
    <label>Condition Set</label>
    <nameField>
        <label>Condition Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condition Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition_Set__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Action</relationshipLabel>
    <relationshipName>Action</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Condition_Set__c/fields/Logical_Statement__c.field-meta.xml
<CustomField>
    <fullName>Logical_Statement__c</fullName>
    <label>Logical Statement</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Condition_Set__c/fields/RPN_Logic__c.field-meta.xml
<CustomField>
    <fullName>RPN_Logic__c</fullName>
    <label>RPN Logic</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Condition_Set__c/fields/Skip_Validation__c.field-meta.xml
<CustomField>
    <fullName>Skip_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Fit_Score__c.field-meta.xml
<CustomField>
    <fullName>Fit_Score__c</fullName>
    <label>Fit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScoringUtilityTest.cls
@isTest
private class ScoringUtilityTest {

    @testSetup
    static void createScoringRules() {
        List<Action__c> actions = new List<Action__c>();
        Action__c action1 = new Action__c(
            Action_Type__c = ScoringUtility.SCORING_ACTION,
            Positive__c = true,
            Score_Type__c = ScoringUtility.FIT_SCORE_TYPE,
            Value__c = 10);
        Action__c action2 = new Action__c(
            Action_Type__c = ScoringUtility.SCORING_ACTION,
            Positive__c = false,
            Score_Type__c = ScoringUtility.ENGAGEMENT_SCORE_TYPE,
            Value__c = 5);
        actions.add(action1);
        actions.add(action2);
        insert actions;

        List<Condition_Set__c> conditionSets = new List<Condition_Set__c>();
        Condition_Set__c conditionSet1 = new Condition_Set__c(
            Action__c = action1.Id,
            Logical_Statement__c = '1',
            RPN_Logic__c = '1',
            Object_Type__c = 'Lead',
            Skip_Validation__c = true);
        Condition_Set__c conditionSet2 = new Condition_Set__c(
            Action__c = action2.Id,
            Logical_Statement__c = '1',
            RPN_Logic__c = '1',
            Object_Type__c = 'CampaignMember',
            Skip_Validation__c = true);

        conditionSets.add(conditionSet1);
        conditionSets.add(conditionSet2);
        insert conditionSets;

        List<Condition_Line_Item__c> conditionLineItems = new List<Condition_Line_Item__c>();
        Condition_Line_Item__c conditionLI1 = new Condition_Line_Item__c(
            Condition_Set__c = conditionSet1.Id,
            Field__c = 'Industry',
            Field_Type__c = 'STRING',
            Operand__c = 'Transportation',
            Operator__c = '=',
            Rule_Number__c = 1,
            Skip_Validation__c = true);
        Condition_Line_Item__c conditionLI2 = new Condition_Line_Item__c(
            Condition_Set__c = conditionSet2.Id,
            Field__c = 'Status',
            Field_Type__c = 'STRING',
            Operand__c = 'Sent',
            Operator__c = '=',
            Rule_Number__c = 1,
            Skip_Validation__c = true);

        conditionLineItems.add(conditionLI1);
        conditionLineItems.add(conditionLI2);
        insert conditionLineItems;

        Campaign testCampaign = new Campaign(
            Name = 'Test Campaign');
        insert testCampaign;
    }

    @isTest
    static void testLeadInsert() {
        Lead newLead = new Lead(LastName = 'Schulz', Industry = 'Transportation', Company = 'CTD');
        insert newLead;
        System.assert(newLead.LastName == 'Schulz');
        Campaign camp = [SELECT Id FROM Campaign LIMIT 1];
        CampaignMember newCM = new CampaignMember(Status = 'Sent', 
            LeadId = newLead.Id, 
            CampaignId = camp.Id);
        insert newCM;
        ScoringUtility su = new ScoringUtility();
        List<Lead> leadsToScore = [SELECT Id, Engagement_Score__c, Fit_Score__c, Industry, (SELECT Id, Status FROM CampaignMembers) FROM Lead];
        su.scoreLeads(leadsToScore);
        update leadsToScore;
        newLead = [SELECT Id, Fit_Score__c, Engagement_Score__c FROM Lead WHERE Id = :newLead.Id];
        System.assertEquals(newLead.Fit_Score__c, 10, 'Lead Fit Score Wrong');
        System.assertEquals(newLead.Engagement_Score__c, -5, 'Lead Engagement Score Wrong');
    }

}